# Generated by Django 6.0.3 on 2026-03-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100, verbose_name='Social network ID')),
                ('channel', models.CharField(choices=[('vk', 'VK'), ('web', 'Web'), ('telegram', 'Telegram')], default='vk', max_length=20, verbose_name='Channel')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True, verbose_name='Gender')),
                ('platforms', models.JSONField(blank=True, default=list, verbose_name='Platforms')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered at')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Last active')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['external_id', 'channel'], name='core_user_externa_e5120e_idx'), models.Index(fields=['last_active'], name='core_user_last_ac_f318ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('external_id', 'channel'), name='unique_user_per_channel')],
            },
        ),
    ]
