# Generated by Django 6.0.3 on 2026-03-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.JSONField(blank=True, help_text='Сырой JSON от Qwen', verbose_name='Recipe')),
                ('dry_sum', models.FloatField(blank=True, help_text='Flour + other dry ingredients (grams)', null=True, verbose_name='Dry sum')),
                ('wet_sum', models.FloatField(blank=True, help_text='Water + oil + other liquids (grams)', null=True, verbose_name='Liquid sum')),
                ('hydration', models.FloatField(blank=True, help_text='(wet_sum / dry_sum) * 100', null=True, verbose_name='Hydration %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='core.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_recipe_user_id_68768f_idx'), models.Index(fields=['hydration'], name='core_recipe_hydrati_a77561_idx')],
            },
        ),
    ]
