# Generated by Django 6.0.3 on 2026-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dry_sum',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='wet_sum',
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
