# Generated by Django 6.0.3 on 2026-03-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_recipe_dry_sum_remove_recipe_wet_sum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='title',
        ),
    ]
