# Generated by Django 6.0.3 on 2026-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='parent',
        ),
        migrations.AddField(
            model_name='recipe',
            name='parents',
            field=models.JSONField(blank=True, default=list, verbose_name='Parents'),
        ),
    ]
