# Generated by Django 6.0.3 on 2026-09-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('unfinished', 'Unfinished')], default='unfinished', help_text='Статус выпечки', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания сессии', verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Update time')),
                ('recipe', models.ForeignKey(help_text='Рецепт, который был выпечен', on_delete=django.db.models.deletion.CASCADE, related_name='baking_sessions', to='core.recipe', verbose_name='Recipe')),
                ('user', models.ForeignKey(help_text='Пользователь, который выпёк', on_delete=django.db.models.deletion.CASCADE, related_name='baking_sessions', to='core.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Baking Session',
                'verbose_name_plural': 'Baking Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_baking_user_id_d2a7b5_idx')],
            },
        ),
    ]
