# Generated by Django 6.0.3 on 2026-09-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bakingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Текст заметки или ссылка на фото в VK', verbose_name='Note')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('text', 'Text')], help_text='Тип заметки (обязательно): text или photo', max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заметки', verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Update time')),
                ('baking_session', models.ForeignKey(help_text='Сессия выпечки, к которой относится заметка', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.bakingsession', verbose_name='Baking Session')),
            ],
            options={
                'verbose_name': 'Baking Note',
                'verbose_name_plural': 'Baking Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['baking_session', '-created_at'], name='core_baking_baking__8abaed_idx')],
            },
        ),
    ]
