events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            #root /static/data/www;
            #index greeting.html;
            proxy_pass http://192.168.1.10:8888/;
        }

        location /images/ {
            root /static/data;
            autoindex on;
        }
    }
}